apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: csi-cfsturbo-pod-dynamic
  name: csi-cfsturbo-pod-dynamic
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: csi-cfsturbo-pod-dynamic
  template:
    metadata:
      labels:
        k8s-app: csi-cfsturbo-pod-dynamic
    spec:
      containers:
        - image: nginx
          name: csi-cfsturbo
          volumeMounts:
            - mountPath: /csi-cfsturbo
              name: csi-cfsturbo
      volumes:
        - name: csi-cfsturbo
          persistentVolumeClaim:
            claimName: csi-cfsturbo-pvc-dynamic
