kind: Service
apiVersion: v1
metadata:
  name: csi-chdfsplugin-external-runner
  namespace: kube-system
  labels:
    app: csi-chdfsplugin-external-runner
spec:
  selector:
    app: csi-chdfsplugin-external-runner
  ports:
    - name: dummy
      port: 12345

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-chdfsplugin-external-runner
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-chdfsplugin-external-runner
  template:
    metadata:
      labels:
        app: csi-chdfsplugin-external-runner
    spec:
      serviceAccount: csi-chdfs-tencentcloud
      containers:
        - name: csi-provisioner
          image: ccr.ccs.tencentyun.com/ccs-dev/csi-provisioner:v1.6.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - mountPath: /var/lib/csi/sockets/pluginproxy/
              name: socket-dir
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 50Mi
        - name: csi-attacher
          image: ccr.ccs.tencentyun.com/ccs-dev/csi-attacher:1.0.1
          args:
            - "--v=3"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-resizer
          image: ccr.ccs.tencentyun.com/ccs-dev/csi-resizer:v0.5.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 50Mi
        - name: chdfs
          image: ccr.ccs.tencentyun.com/ccs-dev/csi-plugin-chdfs:v1.0.0
          env:
            - name: TENCENTCLOUD_CBS_API_SECRET_ID
              valueFrom:
                secretKeyRef:
                  name: csi-tencentcloud
                  key: TENCENTCLOUD_CBS_API_SECRET_ID
            - name: TENCENTCLOUD_CBS_API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: csi-tencentcloud
                  key: TENCENTCLOUD_CBS_API_SECRET_KEY
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy
      volumes:
        - name: socket-dir
          emptyDir: {}