apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-chdfs-tencentcloud
  namespace: kube-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-chdfs-tencentcloud
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"]
    verbs: ["patch", "update"]
  - apiGroups: [""]
    resources: ["configmaps", "events", "persistentvolumes","persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-chdfs-tencentcloud
subjects:
  - kind: ServiceAccount
    name: csi-chdfs-tencentcloud
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-chdfs-tencentcloud
  apiGroup: rbac.authorization.k8s.io