FROM golang:1.10

ADD . /go/src/github.com/tencentcloud/kubernetes-csi-tencentcloud

WORKDIR /go/src/github.com/tencentcloud/kubernetes-csi-tencentcloud

RUN go build -v --ldflags '-linkmode external -extldflags "-static"' -o /go/src/bin/csi-tencentcloud cmd/cbs/main.go


FROM alpine:3.6

RUN apk add --no-cache ca-certificates e2fsprogs

COPY --from=0 /go/src/bin/csi-tencentcloud /csi-tencentcloud-cbs

CMD ["/csi-tencentcloud-cbs"]