apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: new-snapshot-demo
spec:
  snapshotClassName: cbs-snapclass
  source:
    name: csi-pvc
    kind: PersistentVolumeClaim
