apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-goosefs-lite-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  # You can specify the pv name manually or just let kubernetes to bind the pv and pvc.
  volumeName: csi-goosefs-lite-pv
  # goosefs-lite only supports static provisioning, the StorageClass name should be empty.
  storageClassName: ""
