apiVersion: v1
kind: PersistentVolume
metadata:
  name: csi-cfsturbo-pv-static
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  csi:
    driver: com.tencent.cloud.csi.cfsturbo
    # volumeHandle in PV must be unique, use pv name is better
    volumeHandle: csi-cfsturbo-pv-static
    volumeAttributes:
      # cfs turbo rootdir
      rootdir: /cfs
      # cfs turbo fsid (not cfs id)
      fsid: "********"
      # cfs turbo server ip
      host: "*.*.*.*"
      # cfs turbo subPath
      path: /
  storageClassName: ""
