apiVersion: v1
kind: Pod
metadata:
    name: pod-chdfs
spec:
  containers:
  - name: pod-chdfs
    command: ["tail", "-f", "/etc/hosts"]
    image: "centos:latest"
    volumeMounts:
    - mountPath: /data
      name: chdfs
    resources:
      requests:
        memory: "50Mi"
        cpu: "0.1"
  volumes:
  - name: chdfs
    persistentVolumeClaim:
      # Replaced by your pvc name.
      claimName: pvc-chdfs
