apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-chdfs
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    driver: com.tencent.cloud.csi.chdfs
    # Specify a unique volumeHandle like pv name or bucket name.
    volumeHandle: pv-chdfs
    volumeAttributes:
      # Allow other users to access [true/false].
      allowother: "true"
      # Any modification of memory will be synchronized to CHDFS in real time [true/false].
      sync: "fasle"
      # Display details of fuse interface calls [true/false].
      debug: "true"
      # The name of configMap.
      configmapname: "chdfs-config"
      # The namespace of configMap.
      configmapnamespaces: "kube-system"
