apiVersion: v1
kind: PersistentVolume
metadata:
  name: csi-chdfs-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  csi:
    driver: com.tencent.cloud.csi.chdfs
    # Specify a unique volumeHandle like pv name or filesystem id.
    volumeHandle: csi-chdfs-pv
    volumeAttributes:
      # Allow other users to access [true/false].
      allowother: "true"
      # Any modification of memory will be synchronized to CHDFS in real time [true/false].
      sync: "false"
      # Display details of fuse interface calls [true/false].
      debug: "true"
      # The mount url of chdfs mount point.
      url: "*.chdfs.ap-*.myqcloud.com"
      # Additional args.
      additional_args: ""
  storageClassName: ""
