apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-cfsplugin-static
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  csi:
    driver: com.tencent.cloud.csi.cfs
    volumeHandle: data-cfsplugin-static
    volumeAttributes: 
      host: 10.0.0.116
      path: /
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-cfsplugin-static
spec:
  storageClassName: ""
  volumeName: data-cfsplugin-static
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx 
spec:
  containers:
  - image: ccr.ccs.tencentyun.com/qcloud/nginx:1.9
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /var/www
        name: data-cfsplugin-static
  volumes:
  - name: data-cfsplugin-static
    persistentVolumeClaim:
      claimName: data-cfsplugin-static

